name: news

permissions:
  contents: write


on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * *'
jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install all necessary packages
      run: pip install jupyter lxml pandas requests beautifulsoup4 html5lib
    - name: Scraping aj's data
      run: python "aj_scraper.py" 
    - name: Scraping bbc's data
      run: python "bbc_scraper.py"
    - name: Scraping le monde's english data
      run: python "lm_scraper.py"
    - name: Scraping the economist's data
      run: python "the_economist_scraper.py"
    - name: Commit and push any changes
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
